AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-cluster

  MyApiTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: myapi-task
      NetworkMode: bridge
      RequiresCompatibilities:
        - EC2
      ContainerDefinitions:
        - Name: myapi
          Image: 058264167073.dkr.ecr.us-east-1.amazonaws.com/investment-funds-api:latest
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
          Memory: 512
          Cpu: 256

  MyApiService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref MyCluster
      DesiredCount: 1
      LaunchType: EC2
      TaskDefinition: !Ref MyApiTaskDefinition

Outputs:
  ApiServiceURL:
    Description: "URL of the API Service"
    Value: !Sub "http://${MyApiService.Arn}"
